-- Sequências
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATIVO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INCIDENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1;

-- Tabela de Usuários
CREATE TABLE TB_USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NM_USUARIO VARCHAR2(100) NOT NULL,
    DS_EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    DS_SENHA VARCHAR2(100) NOT NULL,
    DS_CARGO VARCHAR2(50),
    DS_DEPARTAMENTO VARCHAR2(50),
    DT_CRIACAO TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP
);

-- Tabela de Locais
CREATE TABLE TB_LOCAL (
    ID_LOCAL NUMBER PRIMARY KEY,
    NM_LOCAL VARCHAR2(100) NOT NULL,
    DS_ENDERECO VARCHAR2(200),
    DS_CIDADE VARCHAR2(50),
    DS_ESTADO VARCHAR2(50),
    DS_PAIS VARCHAR2(50),
    DS_CEP VARCHAR2(10),
    NR_LATITUDE NUMBER,
    NR_LONGITUDE NUMBER,
    DT_CRIACAO TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP
);

-- Tabela de Ativos
CREATE TABLE TB_ATIVO (
    ID_ATIVO NUMBER PRIMARY KEY,
    NM_ATIVO VARCHAR2(100) NOT NULL,
    DS_TIPO VARCHAR2(50),
    DS_NUMERO_SERIE VARCHAR2(50),
    DS_FABRICANTE VARCHAR2(100),
    DS_MODELO VARCHAR2(100),
    DS_STATUS VARCHAR2(20),
    DT_AQUISICAO TIMESTAMP,
    DT_CRIACAO TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP
);

-- Tabela de Incidentes
CREATE TABLE TB_INCIDENTE (
    ID_INCIDENTE NUMBER PRIMARY KEY,
    DS_TITULO VARCHAR2(100) NOT NULL,
    DS_DESCRICAO VARCHAR2(4000),
    NR_SEVERIDADE NUMBER NOT NULL,
    DS_STATUS VARCHAR2(20),
    DS_TIPO VARCHAR2(50),
    DT_OCORRENCIA TIMESTAMP,
    DT_RESOLUCAO TIMESTAMP,
    DT_CRIACAO TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    ID_USUARIO NUMBER NOT NULL,
    ID_LOCAL NUMBER NOT NULL,
    CONSTRAINT FK_INCIDENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
    CONSTRAINT FK_INCIDENTE_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES TB_LOCAL(ID_LOCAL)
);

-- Tabela de Relacionamento Incidente-Ativo
CREATE TABLE TB_INCIDENTE_ATIVO (
    ID_INCIDENTE NUMBER,
    ID_ATIVO NUMBER,
    PRIMARY KEY (ID_INCIDENTE, ID_ATIVO),
    CONSTRAINT FK_INCIDENTE_ATIVO_INCIDENTE FOREIGN KEY (ID_INCIDENTE) REFERENCES TB_INCIDENTE(ID_INCIDENTE),
    CONSTRAINT FK_INCIDENTE_ATIVO_ATIVO FOREIGN KEY (ID_ATIVO) REFERENCES TB_ATIVO(ID_ATIVO)
);

-- Tabela de Alertas
CREATE TABLE TB_ALERTA (
    ID_ALERTA NUMBER PRIMARY KEY,
    DS_TITULO VARCHAR2(100) NOT NULL,
    DS_MENSAGEM VARCHAR2(4000),
    NR_PRIORIDADE NUMBER NOT NULL,
    DS_STATUS VARCHAR2(20),
    DS_TIPO VARCHAR2(50),
    DT_CRIACAO TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    DT_LEITURA TIMESTAMP,
    ID_INCIDENTE NUMBER NOT NULL,
    CONSTRAINT FK_ALERTA_INCIDENTE FOREIGN KEY (ID_INCIDENTE) REFERENCES TB_INCIDENTE(ID_INCIDENTE)
);
